server:
  port: 8200
  
spring:
  application:
    name: tutorials-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"